version: "3.1"

services:
  
  betisier_php:
    container_name: betisier_php
    image: "sylvainmetayer/betisier-php:latest"
    build: "./betisier-php/"
    volumes:
        - ./src:/var/www/html/:rw
        - ./conf/config.inc.php:/var/www/html/include/config.inc.php:rw
    ports:
      - 127.0.0.1:8080:9000
    depends_on:
      - betisier_db

  betisier_db:
    container_name: betisier_db
    image: "sylvainmetayer/betisier-mysql:latest"
    build: "./betisier-mysql/"
    env_file:
        - db.env
    networks:
      - internal
