version: "3.1"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "127.0.0.1:8080:80"
    volumes:
        - ./src:/var/www/html/betisier:rw
        - ./conf/config.inc.php:/var/www/html/betisier/include/config.inc.php:rw
        - ./conf/test.sylvainmetayer.fr.conf:/etc/nginx/conf.d/test.sylvainmetayer.fr.conf

networks:
  default:
    external:
        name: nginx-network

# docker network create nginx && docker-compose up -d --build && docker-compose -f docker-compose.app.yml up -d --build
# docker stop $(docker ps -a -q) && docker system prune -a