version: "3.1"

services:
  
  betisier_php:
    container_name: betisier_php
    image: "sylvainmetayer/betisier-php:latest"
    build: "./betisier-php/"
    volumes:
        - ./src:/var/www/html/:rw
        - ./conf/config.inc.php:/var/www/html/include/config.inc.php:rw
    labels:
      - traefik.backend=betisier_php
      - traefik.frontend.rule=Host:test.sylvainmetayer.fr
      - traefik.docker.network=traefik
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.passHostHeader=true
      # Security headers
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.SSLHost=test.sylvainmetayer.fr
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true
      - traefik.frontend.headers.browserXSSFilter=true
    networks:
      - traefik
      - internal
    depends_on:
      - betisier_db

  betisier_db:
    container_name: betisier_db
    image: "sylvainmetayer/betisier-mysql:latest"
    build: "./betisier-mysql/"
    env_file:
        - db.env
    networks:
      - internal

networks:
  traefik:
    external: true
  internal:
    external: false