version: "3.1"

services:
  
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "127.0.0.1:8080:80"
    volumes:
        - ./src:/var/www/html/betisier:rw
        - ./conf/config.inc.php:/var/www/html/betisier/include/config.inc.php:rw
        - ./conf/test.sylvainmetayer.fr.conf:/etc/nginx/conf.d/test.sylvainmetayer.fr.conf
    depends_on:
      - db
      - php

  php:
    build: "./betisier-php/"
    image: "sylvainmetayer/betisier-php:latest"
    container_name: betisier
    volumes:
        - ./src:/var/www/html/betisier:rw
        - ./conf/config.inc.php:/var/www/html/betisier/include/config.inc.php:rw
    depends_on:
      - db

  db:
    container_name: db
    image: "sylvainmetayer/betisier-mysql:latest"
    env_file:
        - db.env
    build: "./betisier-mysql/"

    