version: "3.1"

services:
  
  php:
    container_name: betisier
    image: "sylvainmetayer/betisier-php:latest"
    build: "./betisier-php/"
    volumes:
        - ./src:/var/www/html/betisier:rw
        - ./conf/config.inc.php:/var/www/html/betisier/include/config.inc.php:rw
    depends_on:
      - db

  db:
    container_name: db
    image: "sylvainmetayer/betisier-mysql:latest"
    build: "./betisier-mysql/"
    env_file:
        - db.env

networks:
  default:
    external:
        name: nginx-network
