logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = "0.0.0.0:80"
  compress = true
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = "0.0.0.0:443"
    [entryPoints.https.tls]

  [entryPoints.ping]
  address = "0.0.0.0:8082"

  [entryPoints.adminPanel]
  address = "127.0.0.1:8083"

[ping]
entryPoint = "ping"

[api]
entryPoint = "adminPanel"
  [api.auth.basic]
    users = ["ocyhc:$apr1$yshixKUc$kxbRgn0Q6dZXbxcCXhO6K/"]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false

[acme]
email = "YOUR_EMAIL@somewhere.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
[acme.httpChallenge]
entryPoint = "http"
